// <auto-generated />
using APP_avanzo.Server.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APP_avanzo.Server.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    partial class AplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APP_avanzo.Server.data.Calcular2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<float>("Promedio_Avanzo_Ciencias")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Avanzo_Lenguaje")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Avanzo_Mate")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Avanzo_Sociales")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Final")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Inall_Ciencias")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Inall_Lenguaje")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Inall_Mate")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_Inall_Sociales")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_final_Ciencias")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_final_Lenguaje")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_final_Mate")
                        .HasColumnType("real");

                    b.Property<float>("Promedio_final_Sociales")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Calculos");
                });
#pragma warning restore 612, 618
        }
    }
}
